//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/LoginMsg.proto
namespace proto.LoginMsg
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MsgLogin")]
  public partial class MsgLogin : global::ProtoBuf.IExtensible
  {
    public MsgLogin() {}
    
    private string _id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private bool _isLoginSuccess = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"isLoginSuccess", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isLoginSuccess
    {
      get { return _isLoginSuccess; }
      set { _isLoginSuccess = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}